### ISSUE TITLE
Static Charge Crash

### ISSUE THREAD

**Issue by keonikoa** [xoxfaby/MoreItems#1]
**Describe the bug**
If an enemy has the item Static Charge, they gain Charges incredibly fast (as they are under constant attack by the player or by drones/DoTs) that lags and then crashes the game real quick.

**MoreItems Version**
I'm using Version 1.14

**Additional information**
I've had this happen to me three times (Twice during the last phase of Mithrix, and once with an Imp Vanguard from ChensClassicItems)

[LogOutput.log](https://github.com/xoxfaby/MoreItems/files/5455631/LogOutput.log)

**Comment by ApoloPZ** [comment]
happened to me too, while using the artifact of vengeance and having a Static Charge.

**Comment by xoxfaby** [comment]
I'm assuming this is fixed now, if not feel free to reopen with new info
