### ISSUE TITLE
Cracked orb interaction with Razorwire

### ISSUE THREAD

**Issue by ApoloPZ** [xoxfaby/MoreItems#2]
Bug description:
Razorwire stops working when one or more Cracked orb(s) are picked up

This error shows in the log each time HP is lost, either by an enemy's attack, or by a self damaging skill or equipment:

[Error  : Unity Log] ArgumentNullException: Value cannot be null.
Parameter name: collection
Stack trace:
System.ThrowHelper.ThrowArgumentNullException (System.ExceptionArgument argument) (at <2fa7a6a452ca43df998f07fd1486c0df>:0)
System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) (at <2fa7a6a452ca43df998f07fd1486c0df>:0)
MoreItems.CrackedOrb.OrbManager_AddOrb (On.RoR2.Orbs.OrbManager+orig_AddOrb orig, RoR2.Orbs.OrbManager self, RoR2.Orbs.Orb orb) (at <dace2ae83b594582b8e66b446c369af3>:0)
DMD<>?2042437120.Hook<RoR2.Orbs.OrbManager::AddOrb>?-1689953408 (RoR2.Orbs.OrbManager , RoR2.Orbs.Orb ) (at <44793ad723c8497b9e09986fea592f1a>:0)
DMD<TakeDamage>?2042437120._RoR2_HealthComponent::TakeDamage (RoR2.HealthComponent this, RoR2.DamageInfo damageInfo) (at <598918f6851444f7a4a62f79462b1ccc>:0)
DMD<>?2042437120.Trampoline<RoR2.HealthComponent::TakeDamage>?1321377792 (RoR2.HealthComponent , RoR2.DamageInfo ) (at <9edc92ad930f4cfe8a392245fcf3beb5>:0)
MoreItems.SerratedKnife.hook_HealthComponent_TakeDamage (On.RoR2.HealthComponent+orig_TakeDamage orig, RoR2.HealthComponent self, RoR2.DamageInfo damageInfo) (at <dace2ae83b594582b8e66b446c369af3>:0)
DMD<>?2042437120.Hook<RoR2.HealthComponent::TakeDamage>?21338496 (RoR2.HealthComponent , RoR2.DamageInfo ) (at <99651312fd114d65ae5633bf64a797bf>:0)
DMD<>?2042437120.Trampoline<RoR2.HealthComponent::TakeDamage>?851978240 (RoR2.HealthComponent , RoR2.DamageInfo ) (at <217e58472ab8475e8c6f3abd07c8f6b5>:0)
MoreItems.StaticCharge.hook_HealthComponent_TakeDamage (On.RoR2.HealthComponent+orig_TakeDamage orig, RoR2.HealthComponent self, RoR2.DamageInfo damageInfo) (at <dace2ae83b594582b8e66b446c369af3>:0)
DMD<>?2042437120.Hook<RoR2.HealthComponent::TakeDamage>?62834560 (RoR2.HealthComponent , RoR2.DamageInfo ) (at <a04ad4382aa74d549a36d3eb303f8a1f>:0)
DMD<>?2042437120.Trampoline<RoR2.HealthComponent::TakeDamage>?2064204800 (RoR2.HealthComponent , RoR2.DamageInfo ) (at <1b840b186bd646ba9e66a0ab53a8eb17>:0)
MoreItems.CrackedOrb.HealthComponent_TakeDamage (On.RoR2.HealthComponent+orig_TakeDamage orig, RoR2.HealthComponent self, RoR2.DamageInfo damageInfo) (at <dace2ae83b594582b8e66b446c369af3>:0)
DMD<>?2042437120.Hook<RoR2.HealthComponent::TakeDamage>?-1915899264 (RoR2.HealthComponent , RoR2.DamageInfo ) (at <7c7a484c7d6a4c679bfcbdccc8a6d132>:0)
DMD<>?2042437120.Trampoline<RoR2.HealthComponent::TakeDamage>?-162694144 (RoR2.HealthComponent , RoR2.DamageInfo ) (at <4287a5d049ae403b88d8ccbc85487486>:0)
MoreItems.SerratedSpoon.hook_HealthComponent_TakeDamage (On.RoR2.HealthComponent+orig_TakeDamage orig, RoR2.HealthComponent self, RoR2.DamageInfo damageInfo) (at <dace2ae83b594582b8e66b446c369af3>:0)
DMD<>?2042437120.Hook<RoR2.HealthComponent::TakeDamage>?-21102592 (RoR2.HealthComponent , RoR2.DamageInfo ) (at <9c4ef31e01d949b4a800033a2c5c1519>:0)
EntityStates.Treebot.Weapon.FirePlantSonicBoom.OnEnter () (at <61219714c53949e985731f1a5b7cd7a8>:0)
RoR2.EntityStateMachine.SetState (EntityStates.EntityState newState) (at <61219714c53949e985731f1a5b7cd7a8>:0)
RoR2.EntityStateMachine.FixedUpdate () (at <61219714c53949e985731f1a5b7cd7a8>:0)

Mods:
only MoreItems and dependencies

**MoreItems Version**
Mod Version 1.6.15

**Comment by xoxfaby** [comment]
I'm assuming this is fixed now, if not feel free to reopen with new info
