### ISSUE TITLE
Bleed runs out instantly when using Cracked Orb.

### ISSUE THREAD

**Issue by MagnusHellstrom** [xoxfaby/MoreItems#3]
As the title says.
There isn't anything in the console that specifies a reason, and I'm unsure if it's intentional or not.

**Comment by xoxfaby** [comment]
What attack was it and how many orbs did you have?

Also the next version of the cracked orb won't mess with proc coefficient so I'm not crazy worried about it, I'm just curious

**Comment by MagnusHellstrom** [comment]
> What attack was it and how many orbs did you have?
> 
> Also the next version of the cracked orb won't mess with proc coefficient so I'm not crazy worried about it, I'm just curious

Captain's shotgun, and 2 orbs.

**Comment by xoxfaby** [comment]
Hmm that shotgun already has a lower proc coefficient and with this you'd only have 1/4th of the proc so is it possible that it just ran out in the appropriate amount of time, just that it was very short?

**Comment by MagnusHellstrom** [comment]
> Hmm that shotgun already has a lower proc coefficient and with this you'd only have 1/4th of the proc so is it possible that it just ran out in the appropriate amount of time, just that it was very short?

I would apply 16 odd stacks of bleed, but they would run out before they could even tick for damage.
My mate would stack bleed on top of mine and it would stay perfectly fine, but any that I applied alone would near-instantly vanish.

**Comment by Angular-Angel** [comment]
Huh, it sets the proc to 1/4th normal? That's harsh. Wouldn't halving it make more sense? Or maybe putting it at 40% normal per attack, instead of 50%. :/

**Comment by xoxfaby** [comment]
> Huh, it sets the proc to 1/4th normal? That's harsh. Wouldn't halving it make more sense? Or maybe putting it at 40% normal per attack, instead of 50%. :/

He had 2 stacks

**Comment by xoxfaby** [comment]
Also once again this is moot since the item is getting Reworked

**Comment by Angular-Angel** [comment]
Ohhh, whoops! My mistake. Alright, makes sense now. XD

**Comment by xoxfaby** [comment]
Closed because item was reworked
