### ISSUE TITLE
Incompatibility with MinorUnearthed (Cracked Orb + "To The Stars" Special)

### ISSUE THREAD

**Issue by KdronTheShadow** [xoxfaby/MoreItems#5]
**_MoreItems v2.1.4_** + **_MinorUnearthed_** by **_EnforcerGang_**
I posted an issue on MinerUnearthed's github as well in hopes that wherever the problem lies it can be resolved
which you can find here: https://github.com/ArcPh1r3/MinerUnearthed/issues/3

With the item Cracked Orb the miner's special ability **_To The Stars_** becomes unusable due to the insane duplication of projectiles from the ability freezing / crashing the game.

using bleed stacks from 10 needles and a dps meters I was able to calculate that I had shot over **30,000+ projectiles** in a **single shot** with just **ONE Cracked Orb**, causing my game to hang and then eventually crash.

I believe it could be one of these two logical conclusions, but as I don't know the inner workings of either mod it's just my best guess.

A) self duplication of individual projectiles
high proc chance on individual projectiles that duplicates it almost endlessly
(shoot -> each one then rolls to duplicate -> then each one of the duplicates roll to duplicate -> and so forth)

B) whole duplication of the entire attack
any individual projectiles that succeeds, duplicates an entire new "To The Stars" causing 30 more projectiles.
(shoot 30x -> rolls for any that hit and duplicates the ENTIRE attack again for any that succeed -> shoot 30xNumberThatPassedTheRoll -> and so forth)

Examples

**_24,877 bleed stacks in one shot_** (Look at that **raw** base 12 damage lol)
![20210813144210_1](https://user-images.githubusercontent.com/88908714/129422613-9ccf7227-f8db-412f-9788-fa1c677402f2.jpg)

**DPS from said shot next frame**
![20210813144317_1](https://user-images.githubusercontent.com/88908714/129422627-c7334075-d10b-4142-a705-e8dab7a51aef.jpg)

**Comment by xoxfaby** [comment]
This is very likely due to the mod using a vanilla attack type in an unintended way and its on them to fix, though I'm happy to help them with that process if they need it.

**Comment by KdronTheShadow** [comment]
Thank you for the quick response! Kinda figured it was on the miner itself as stated in the issue I posted on their github. Hope they can resolve it
