### ISSUE TITLE
Sensor Item

### ISSUE THREAD

**Issue by FlareyBoi64** [xoxfaby/MoreItems#9]
What about a sensor-like item (red), that has a chance to make ranged attacks lock onto enemies? Well besides Railgunner

**Comment by xoxfaby** [comment]
Unfortunately, with the way attacks work, I think this would be almost impossible to implement. I already have an item that modifies every attack so I'm in a pretty good position to comment on that and I don't think this is feasible, unfortunately.

**Comment by FlareyBoi64** [comment]
Alright, good luck on development
